### ISSUE TITLE
Initial Indexer Setup

### ISSUE THREAD

**Issue by mikeAdamss** [GSS-Cogs/linked-data-repository-indexer#2]
Service thats triggered by a message -> converts csvw. + csv to RDF, puts rdf into the specified location.

Dependent on: https://app.zenhub.com/workspaces/features-squad-61b72275ac896c0010a1b00b/issues/gss-cogs/linked-data-repository/15

- [ ] Service Runs Via Dockerfile
- [ ] Get resource_id from queue 
- [ ] Concert to RDF (ttl for now) with [https://github.com/GSS-Cogs/csv2rdf-docker](https://github.com/GSS-Cogs/csv2rdf-docker)
- [ ] Store ttl representation of resource in bucket (ideally aliased to a filepath... but we'll see).
- [ ] Write location of rdf back to the metadata database entry for this resource.
